import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — QuadBrand",
  description: "Terms and conditions for using QuadBrand.",
};

export default function TermsPage() {
  return (
    <div className="pt-32 pb-20 container-narrow min-h-screen">
      <div className="max-w-3xl mx-auto">
        <h1 
          className="text-3xl md:text-4xl font-bold tracking-tight mb-2"
          style={{ fontFamily: "var(--font-outfit), sans-serif" }}
        >
          Terms of Service
        </h1>
        <p className="text-[var(--text-tertiary)] mb-8">Last Updated: June 1, 2026</p>

        <div className="prose prose-invert prose-p:text-[var(--text-secondary)] prose-h2:text-[var(--text-primary)] prose-h2:font-bold prose-h2:mt-8 prose-h2:mb-4 prose-a:text-[var(--accent-cyan)] max-w-none">
          <p>
            Welcome to QuadBrand. By accessing our website and using our AI visual generation services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
          </p>

          <h2>1. Service Description</h2>
          <p>
            QuadBrand provides an AI-powered platform that allows users to extract brand guidelines from URLs and generate customized images based on those guidelines using third-party diffusion models.
          </p>

          <h2>2. User Accounts & Credits</h2>
          <p>
            You are responsible for maintaining the security of your account and password. QuadBrand operates on a credit-based system for image generation. Credits purchased via subscription or one-time top-ups are non-refundable unless required by law.
          </p>

          <h2>3. Intellectual Property Rights</h2>
          <p>
            <strong>Your Output:</strong> Subject to your compliance with these Terms, QuadBrand assigns you all its right, title, and interest in and to the images generated by the AI using your prompts and brand data. You are free to use these images for commercial purposes.
          </p>
          <p>
            <strong>Our Technology:</strong> The QuadBrand platform, its original code, logos, and UI are the intellectual property of QuadBrand and are protected by copyright laws.
          </p>

          <h2>4. Acceptable Use</h2>
          <p>
            You agree not to use QuadBrand to generate content that is:
          </p>
          <ul>
            <li>Illegal, harmful, threatening, or abusive</li>
            <li>Sexually explicit or pornographic</li>
            <li>Infringing on the intellectual property rights of third parties</li>
            <li>Intended to deceive or spread misinformation</li>
          </ul>
          <p>
            We reserve the right to suspend or terminate accounts that violate these guidelines without prior notice or refund.
          </p>

          <h2>5. Limitation of Liability</h2>
          <p>
            QuadBrand is provided "as is" without any warranties. We do not guarantee that the AI-generated images will be flawless or meet your exact expectations. In no event shall QuadBrand be liable for any indirect, incidental, or consequential damages arising out of your use of the service.
          </p>

          <h2>6. Changes to Terms</h2>
          <p>
            We may modify these Terms at any time. We will notify users of significant changes via email or an in-app notice.
          </p>
        </div>
      </div>
    </div>
  );
}
